"""empty message

Revision ID: 126a588b784
Revises: 194cfa6c4e5
Create Date: 2014-04-11 12:31:35.684420

"""

# revision identifiers, used by Alembic.
revision = '126a588b784'
down_revision = '194cfa6c4e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
