"""empty message

Revision ID: 194cfa6c4e5
Revises: 252461eecab
Create Date: 2014-04-10 12:11:42.807757

"""

# revision identifiers, used by Alembic.
revision = '194cfa6c4e5'
down_revision = '252461eecab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_table('poop')
    ### end Alembic commands ###
