"""empty message

Revision ID: 252461eecab
Revises: 444f50ac3ca
Create Date: 2014-04-10 00:58:51.004544

"""

# revision identifiers, used by Alembic.
revision = '252461eecab'
down_revision = '444f50ac3ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    ### end Alembic commands ###
